### ISSUE TITLE
Wallet do not recover properly from a backup

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1096] opened 2018-01-24 00:56 UTC
1) I've created a clean wallet, sent 251k tstrat to it, made a backup
2) Created bunch of txes to myself => got 400 UTXOs and 50mb wallet file
3) replaced 50mb wallet file with the backup
when the wallet synced it said I have 247k and 10 UTXOs. so it did not recover from the backup well.

Here is the first tx that splits 251k into several small ones: 
https://chainz.cryptoid.info/strat-test/tx.dws?564517.htm
if you follow the transaction 2-3 layers in depth you will find around 400txes that are not redeemed. 

after the wallet recovery my wallet sees only this UTXOs:
`Address: TX9HCTc7SvSFS9qMu6686NhwMpgVUSraFB Amount: 247081.99715561 | Address: TH26SbKKfXKD7wHUU4CE4bZATAYzQMqNwm Amount: 9.99571051 | Address: TYgpzmbVZ8y1k8kwepCHDtLg1qdHRP2P18 Amount: 9.99723616 | Address: TJQzTFSb57E59rDheX2K8dDt9W9StuaYtw Amount: 9.99731221 | Address: TYgRM8KS7FJWdr7o3ScENeNxkzusyDxxXB Amount: 9.94652062 | Address: TB5j9naEkVxHGicagR4JNkxN9nEmZYhDPe Amount: 9.98981354 | Address: TLpNdPJ7G9yk5TeRUcDoBLA5vPf8umdd6Y Amount: 9.99045421 | Address: TD5HfTkYha5DbEbaSkhbXxxQVYVytZ9Ub1 Amount: 9.99146990 | Address: TMyfeD61Wdo6sD5LAvE76PyrbQkhJvLxcq Amount: 9.99430228 | Address: TPZQRdRxwbjVexwFKvfTBrC4wRF2RnVhe2 Amount: 9.99813972 | Address: THV8vWTowKhHjqsHyec8EjQQVD6d4heQva Amount: 9.99822403`

this is the branch that has code for reproducing this bug: 
https://github.com/noescape00/StratisBitcoinFullNode/tree/txFlud

This maybe caused due to a large amount of UTXOs OR because special type of txs was used- I've created txes with 20-200 outputs instead of usual 1-2. Anyway both scenarios should be well supported.

**Comment by dangershony** [comment] 2018-01-24 12:54
@bokobza

**Comment by noescape00** [comment] 2018-01-25 16:57
When we're syncing the wallet we process every block and every tx of that block => WalletManager.ProcessTransaction. 
ProcessTransaction checks each output if it belongs to us and it uses 'keysLookup' to do so. And keysLookup is a combined collection of all wallet's account's external and internal addresses. 
And by default we create WalletManager.UnusedAddressesBuffer (which is 20) amount of addresses for each account. 

So the bug happens when we process a tx with, like, 200 UTXOs in it and all of them are ours we are getting only the 20 of them and ignore the rest because we are not aware that they are ours. 

In order to test if that is the case I've changed UnusedAddressesBuffer to be 400 and I ran the wallet recovery- it was able to recover all  251k tstrat worth of UTXOs.

**Comment by noescape00** [comment] 2018-01-25 17:06
So I think a good way to fix it is to always have amount of unused addresses for each account that is equal to the amount of outputs of tx that we're processing. 

But we can't do that with current wallet logic because after a single block with large outputs count is consumed we will end up with wallet containing huge amount of unused addresses- so the wallet will become big. 

So probably we should approach this differently- do not keep addresses that were never used at all- don't save them in the wallet file. On tx processing just generate as many as we need- check if tx's outputs are ours and remove unused addresses. 

@dangershony  @bokobza what do you think?

**Comment by bokobza** [comment] 2018-02-07 09:28
From a discussion with @noescape00:
- our wallet is bip 44 compatible and therefore having more than 20 unused addresses is not required
- what if the transaction has only 1 output but it's one of our addresses at index 120? We'll miss it. If you wanted to "look further", how far do you go?
- for us to support a number like 100, 200 or 500 unused addresses will make our node slower. Maybe not by much but still.
Closed as not a bug.

**Closed by bokobza** 2018-02-07 09:28 UTC
