### ISSUE TITLE
Discussion: Consensus Validation Rules

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#124] opened 2017-04-25 15:17 UTC
An idea I think can be useful for the consensus code is to break many of the validation logic inside the consensus validator class in to ValidationMacros (or similar) to have smaller snippets of code.

Then on startup a node will load all its consensus validation macros to a container and when a block is received each block will pass in all the macros in order to be considered valid.
A Context will be passed in to every Macro for Macros that need previously calculated data

The benefits:
- Readability - a macro will be named based on its logic (i.e CoinBaseMaturityMacro) 
- Testability - it will be much easier to write tests for each macro
- ReUsability - POW/POS/PO..X consensus rules will be able to reuse macros  
- ChainSpecific - currently POS has hard coded checks for protocol version, that logic is Stratis specific 
- Optimization - some macros will be able to run in parallel  

I don't think there will be any performance degradation on iterating over several tens of macros.
I am also not sure Macro is the right name.

**Comment by Derrick-** [comment] 2017-04-25 15:24
Perhaps they are "Rules"

I think this is a very good idea.

**Comment by dangershony** [comment] 2017-04-25 15:28
Yeah @bokobza also suggested the word Rules I am not against that, so in the folder ValidationRules we'll have say a CoinBaseMaturityRule

**Comment by NicolasDorier** [comment] 2017-04-25 15:37
I think the consensus code is tricky and should be kept as close as possible to bitcoin core to prevent bugs.
The ConsensusValidator class already break out functions that you can reuse outside of the consensus loop.

**Comment by dangershony** [comment] 2017-04-25 15:52
I agree consensus is tricky indeed, and I think an implementation should never run on two languages so the Stratis bitcoin node will never be a replacement for the Bitcoin chain, and after we have the stratis chain running in prod for many good month we may retire the stratis c++ version in favor of the C# version.

So if consensus is not a crusial factor I believe we can safely break it smaller to Rules.

**Comment by Derrick-** [comment] 2017-04-25 18:01
Yes, the way I interpret what you'll be doing is just breaking the consensus rules into separate functions, and this also makes things more testable I hope. They will still all be called from the same place(s)

**Comment by NicolasDorier** [comment] 2017-04-26 06:55
what smaller snippet are you thinking about ? I think the methods are already fairly broken out already in the ConsensusValidator.

**Comment by dangershony** [comment] 2017-04-26 10:40
Some examples may look like this:
```
		public abstract class ConsensusRule
		{
			public abstract void Check(ContextInformation context);
		}

		public class CoinMaturityConsensusRule : ConsensusRule
		{
			public override void Check(ContextInformation context)
			{
				// checking that each trx prev output is not spending
				// the coinbase/coinstake before its mature enough
				// BitcoinCore Consensus Rule Reference:
				// https://github.com/bitcoin/bitcoin/blob/a6548a47a5548b4b43510c548a9418673ab751de/src/validation.cpp#L1332

				foreach (var tx in context.BlockResult.Block.Transactions)
				{
					foreach (TxIn trx in tx.Inputs)
					{
						var prevout = trx.PrevOut;
						var coins = context.Set.AccessCoins(prevout.Hash);

						if (coins.IsCoinbase)
						{
							if (context.BlockResult.ChainedBlock.Height - coins.Height < context.ConsensusOptions.COINBASE_MATURITY)
								ConsensusErrors.BadTransactionPrematureCoinbaseSpending.Throw();
						}

						if (coins.IsCoinstake)
						{
							if (context.BlockResult.ChainedBlock.Height - coins.Height < context.ConsensusOptions.COINBASE_MATURITY)
								ConsensusErrors.BadTransactionPrematureCoinstakeSpending.Throw();
						}
					}
				}
			}
		}

		public class EnforceBIP30 : ConsensusRule
		{
			public override void Check(ContextInformation context)
			{
				// The BIP30 specification does not allow blocks 
				// that contain transactions which 'overwrite' older transactions.
				// BitcoinCore Consensus Rule Reference:
				// https://github.com/bitcoin/bitcoin/blob/a6548a47a5548b4b43510c548a9418673ab751de/src/validation.cpp#L1770

				if (context.Flags.EnforceBIP30)
				{
					foreach (var tx in context.BlockResult.Block.Transactions)
					{
						var coins = context.Set.AccessCoins(tx.GetHash());
						if (coins != null && !coins.IsPrunable)
							ConsensusErrors.BadTransactionBIP30.Throw();
					}
				}
			}
		}

		public class StratisProtocolV3Check : ConsensusRule
		{
			public override void Check(ContextInformation context)
			{
				// Check if the stratis protocol version is valid
				// blocks not in the correct version are rejected  
				// version 3 date is 2016-08-06T07:03:20
				if (!StakeValidator.IsProtocolV3((int)context.BlockResult.ChainedBlock.Header.Time))
				{
					if (context.BlockResult.ChainedBlock.Header.Version > BlockHeader.CURRENT_VERSION)
						ConsensusErrors.BadVersion.Throw();
				}
			}
		}

```

Its much easier to unit test a ConsensusRule separately  

It will be easier to plug rules for different coins as well (see the StratisProtocolV3Check will only be used when building the stratis consensus rules container)

We could also decide to make bigger ConsensusRule classes for example the entire UTXO checks can go in its own ConsensusRule

**Comment by dev0tion** [comment] 2017-04-26 13:40
As I said at the standup, if it doesn't effect the performance I think it's a very good idea.
It will improve testability and re-usability a lot. I prefer Rules over Macros as well.

If you want a bigger ConsensusRule class for e.g. all the UTXO checks we can maybe create a class that utilizes multiple smaller Rules. That would also improve readability.

**Comment by dangershony** [comment] 2017-04-27 16:30
Its not a bad idea, we know for certain that at some point there will be iteration over a block's transactions then there can be a collection of TransactionRule that will have some special parent Rule that will do the iterations.

We could also record each Rules performance, easier to identify bottle necks.

**Comment by NicolasDorier** [comment] 2017-04-28 06:43
@dangershony,  Some rules requires the CoinSet, some not. Some requires the blocks some only the header.
If you break like that then it becomes not obvious what rule need what info.

@dev0tion  I argue that this is already unit testable, as you can already call the different Check methods through the Validator. And a better test unitaire it just to make fake blocks which break some of the rules and see if the error is the expected one.
I argue this is fairly simple test: 1 block = 1 test of consensus rule.

I am suspecting the reason you want that is to add or remove rules depending on whether we are validating a bitcoin block or a stratis one. If it should include the mempool policy rules or not.
I am not sure that in practice it will make the code simpler though.

I think if you really want to do that, you should start by making a test checking all the rules. Then refactor to see if you did not break anything.
Also, it would be better if the code of stratis is not mixed up in a consensus function of Bitcoin. (ie if `coins.IsCoinstake` is true, then add all stratis specific rules)

If you really want to go down that route, you really need 3 differents methods to override for each ConsensusRule. CheckHeader, Check, CheckContextual. First check only header, second only check the block info without the utxo. The third would validate the block against the current utxo.

**Comment by dangershony** [comment] 2017-05-01 21:46
The ContextInformation will have all the data that needs to go down the validation flow (CoinSet, Block, Header, even ChainedBlock)

@NicolasDorier yeah what you propose is very similar to what you already did on consensus (which is currently implemented) and its, understandably, very similar to core. 
I then extended it by overriding some methods for the stratis POS code so there is (almost complete) separation to the bitcoin consensus POW code.

On a broader view we plan to offer side chain technology where sidechains consensus rules will vary, as a blockchain platform we need to make it easy to pick different consensus rules for many blockchains.
(I strongly believe one day in a not too far future we will have many blockchains like we now have many websites)

You might be right though it might make the code more complicated we'll know more when we start to implement the rules.

**Comment by NicolasDorier** [comment] 2017-05-03 06:47
The way the methods are divided right now allow you to make some preliminary validations before the consensus loop, without having access to the coinview. Making only one big method that does everything is a regression, and will ask CoinView when it is not needed. (That you will need to lock)

Some rules does not need the coinview at all. What I would do it you really want to go down the rule path is to have a ValidationRuleSet class and a ValidationRule one, where all rules can override CheckHeader/CheckContextualBlock/CheckBlock. Making one big method for all would be a mistake.

**Comment by dangershony** [comment] 2017-05-03 22:22
> Making one big method for all would be a mistake.

You mean the ```Validate.Check(context)``` method?  indeed one method but broken to many classes with hopefully smaller and less complex logic.

ValidationRuleSet is not a bad idea, that abstract class rule will only be called when the UTXO Set is populated so any implementation that needs the UTXO set will derive form this class and not the more simple ValidationRule.

We could try to start with the POS code, breaking it to smaller ConsensusRules that may give us a feel of how complex this refactor will become.

**Comment by NicolasDorier** [comment] 2017-05-04 09:03
You really need 3 methods. Those three methods are not meant to be used together, except in the consensus.

**Comment by dangershony** [comment] 2017-05-04 13:15
I think I understand what you mean, you intend to have a core consensus rule class with all 3 methods override and any additional rules will only implement the methods they actually need.

**Comment by NicolasDorier** [comment] 2017-05-04 13:23
yes

**Comment by NicolasDorier** [comment] 2017-05-04 13:25
Basically there would be two ValidationRuleSet.

ConsensusRules and PolicyRules. PolicyRules cover Consensus+Mempool rules.
Each rule keep the three methods and implements the methods they are interested in.
It will be nice to read.

**Comment by dangershony** [comment] 2017-05-04 14:06
PolicyRule sounds good.
We have several rule types already.

We just need to distinguish exactly how Policy is different from Consensus.

Different coin types like distinguish a version can qualify as policy

**Comment by dangershony** [comment] 2017-07-03 11:33
![](https://github.trello.services/images/mini-trello-icon.png) [[Mempool] Use Consensus Rules](https://trello.com/c/04syOjkI/3-mempool-use-consensus-rules)

**Comment by dangershony** [comment] 2017-12-04 17:31
Bringing this issue back to live I would like to point out to the suggestion @Aprogiena made on how bulk rules should be registered with the ConsensusRules in this PR https://github.com/stratisproject/StratisBitcoinFullNode/pull/835#issuecomment-348602662

Also @fassadlr suggested to use a validation pattern

**Comment by bokobza** [comment] 2018-04-24 13:15
CLosing this as the development work is already well on its way.

**Comment by bokobza** [comment] 2018-07-10 12:20
That's done.

**Closed by bokobza** 2018-07-10 12:20 UTC
Labels: feature, improvement, sp1
