### ISSUE TITLE
Node failed to recover after a crash

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#2664] opened 2018-11-02 21:52 UTC
A server crash led to an incomplete write to the wallet file and after restart it still fails to recover

```
      An error occurred starting the application.
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Value cannot be null.
Parameter name: block) (Unterminated string. Expected delimiter: ". Path 'accountsRoot[0].accounts[0].internalAddresses[2].transactions[1957].blockHash', line 40818, position 12612815.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 58
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Rules\PosConsensusRuleEngine.cs:line 52
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 201
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 52
```

![image](https://user-images.githubusercontent.com/444711/47942590-5daafa80-deea-11e8-8240-0e0272746e92.png)

**Comment by majikandy** [comment] 2018-11-02 22:29
If I remove the wallet, there is still an error in StakeChainStore where it can't find the block for the 

```
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application.
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Value cannot be null.
Parameter name: block) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\StakeChainStore.cs:line 58
   at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin.Features.Consensus\Rules\PosConsensusRuleEngine.cs:line 52
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in C:\Projects\Stratis\StratisBitcoinFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 201
```

I was able to recover by adding the following line of code to to StakeChainStore in order to rewind coinview 1 block 

``` 
public async Task LoadAsync()
        {
            uint256 hash = await this.dBreezeCoinView.GetTipHashAsync().ConfigureAwait(false);
            ChainedHeader next = this.chain.GetBlock(hash);

            // Rewind coinview one block if next is not in blockstore as it means node must have crashed before it was able to persist to blockstore despite managing to update coinview
            if (next == null)
            {
                hash = await this.dBreezeCoinView.Rewind().ConfigureAwait(false);
                next = this.chain.GetBlock(hash);
            }
```

**Comment by bokobza** [comment] 2018-11-07 14:29
Re the wallet:
that's interesting. Normally, when we save the wallet to the file system, it is first written to a temporary file `walletname.uniqueid.new`, then the wallet file `walletname` is renamed to `walletname.uniqueid.temp` and then `walletname.uniqueid.new` is renamed to `walletname`.
so wherever it fails, there should always be 
**a** file with the wallet content somewhere.
Is that not the case? @majikandy @sondreb 

Here is the code:
https://github.com/stratisproject/StratisBitcoinFullNode/blob/a238bc18bf97bfab93b8e936cd92dc8ed55d53f2/src/Stratis.Bitcoin/Utilities/FileStorage.cs#L38-L70

**Comment by sondreb** [comment] 2018-11-07 15:18
For my home server, that has not been the case. It has written multiple wallets file with zeroes (0) multiple times. I sent some messages to Dan regarding this earlier, and I know the problem is my server which does a hardware reset once in a while (often at least once a day). I'm in the process of replacing the hardware on it to avoid this, so it is really an hardware issue, but still strange that multiple wallets ended up being zeroed.

**Comment by fassadlr** [comment] 2019-02-11 11:51
@bokobza @majikandy I believe this has been fixed?

**Comment by bokobza** [comment] 2019-02-17 23:11
yeah we can close this, the chances of this happening is very slim and it generally shouldn't.

**Closed by bokobza** 2019-02-17 23:11 UTC
Labels: Obsolete, bug, wallet
