### ISSUE TITLE
Getrawtransaction null after recent move of IBlockStore Interface into BlockStoreQueue

### ISSUE THREAD

**Issue by TjadenFroyda** [stratisproject/StratisBitcoinFullNode#1554] opened 2018-06-25 05:43 UTC
Above issue was noted by InterestingBeing Sunday in discord as something than had stopped working between 1.1.11 and 1.1.12; tracked down the issue after confirmed on my end. Details:
The IBlockStore interface was moved to BlockStoreQueue in #1517 from BlockStoreFeature. The getrawtransaction API and RPC methods use GetTrxAsync from the IBlockStore interface, which in turn had called the method in the IBlockRepository interface.  Simple fix would be just to change IBlockStore to IBlockRepository in both classes, however it looks like IBlockRepository is not accessible via this.fullNode.NodeService<> in its current namespace (Stratis.Bitcoin.Features.BlockStore).

Proposed solution (tested & works): 
1) Move the IBlockRespository interface from BlockRepository in Stratis.Bitcoin.Features.BlockStore into it's own file in Stratis.Bitcoin.Interfaces.
2) Update methods that had previously used IBlockStore in NodeController and FullNodeController and related tests to use IBlockRepository directly.
3) Update directives for classes that use IBlockRepository to include the Stratis.Bitcoin.Interfaces namespace.

I've done the above, waiting for integration tests to finish running. All green so far. Would be happy to submit PR if ok with above approach.

**Comment by dangershony** [comment] 2018-06-25 11:42
Ah indeed correct there is a bug

We need to tell the DI that `BlockStoreQueue` is the implementation of `IBlockStore`.

So I'd say the correct way is to add this line in BlockStoreFeature
```                        
services.AddSingleton<BlockStoreQueue>().AddSingleton<IBlockStore, BlockStoreQueue>(provider => provider.GetService<BlockStoreQueue>()); ;
```

Then in the controller constructor
```
        public NodeController(IFullNode fullNode, ILoggerFactory loggerFactory, 
            IDateTimeProvider dateTimeProvider, IChainState chainState, 
            NodeSettings nodeSettings, IConnectionManager connectionManager,
            ConcurrentChain chain, Network network, IPooledTransaction pooledTransaction = null,
            IPooledGetUnspentTransaction pooledGetUnspentTransaction = null,
            IGetUnspentTransaction getUnspentTransaction = null,
            INetworkDifficulty networkDifficulty = null,
            IBlockStore blockStore = null)
        {

```
This will make store available.

**Comment by noescape00** [comment] 2018-06-25 18:37
Strange that we don't have tests that cover all API and RPC methods. Probably also should add some after the issue is fixed.

**Comment by TjadenFroyda** [comment] 2018-06-25 18:53
@dangershony - ahh...I was missing that second step with the DI when I tried that. Much easier :)  @noescape00 - my bad, didn't cover this scenario with my last PR. Could address the tests with this quick fix if you all would like.

**Comment by noescape00** [comment] 2018-06-25 20:23
>Could address the tests with this quick fix if you all would like.

That would be nice, thanks!

**Comment by bokobza** [comment] 2018-07-13 09:21
Fixed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1635

**Closed by bokobza** 2018-07-13 09:21 UTC
Labels: sp1
