### ISSUE TITLE
[RF] Wallet is not notified if the transaction cannot be fulfilled

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1254] opened 2018-03-27 13:39 UTC
When attempting to spend not matured/recently staked coins the transaction is not accepted to the memory pool and the wallet is not notified of this.

As a result the wallet shows that the transaction has been sent and is pending confirmation wheres in fact the transaction was never shared across the network.

**Comment by dangershony** [comment] 2018-03-27 13:50
Ah ok this is a bug and a duplicate of #1255

**Comment by maciejzaleski** [comment] 2018-03-27 13:54
You can say is a duplicate as it is related to the same issue but in general we should have a way to let the wallet know about transactions which cannot be completed for this or other reasons.

**Comment by dangershony** [comment] 2018-04-24 13:01
This task to me is about fixing how we broadcast transactions, three are some issues.

We should move all broadcasting code to the wallet and remove the states (or move them to the light wallet)
The main wallet should relay on memepool
Light wallet can try to rely on ping backs from peers

The implemented of this please make sure to discuss with me and @bokobza

**Comment by bokobza** [comment] 2018-04-24 14:43
This will require integration tests as well.
Ideally we'd have a failing integration test reproducing this scenario first, then work on fixing it.

**Comment by ferdeen** [comment] 2018-04-27 13:06
After creating the integration test (not committed yet), when trying to spend CoinStake before maturity the exception is throw here in PosConsensusValidator.CheckMaturity().  This doesn't get caught by the WalletController and is why the UI doesn't report the failure.  

![image](https://user-images.githubusercontent.com/16000683/39363839-9f15b034-4a23-11e8-97c6-1fecd27e07d3.png)

As Dan mentioned above we need to see how to broadcast this so that the wallet manager picks up the failed transaction.  Which I am working on.

**Closed** 2018-05-08 14:30 UTC
Labels: High Priority, Refactor, bug, sp1
