### ISSUE TITLE
UpdateUTXOSet always null

### ISSUE THREAD

**Issue by alfhv** [stratisproject/StratisBitcoinFullNode#1978] opened 2018-08-21 17:50 UTC
I have an exception throw because RuleContext.UpdateUTXOSet is always null. I have tried deleting all chain data but always the same. Due to this exception the consensus always crash and there is no wallet  synchronization.
OS: Windows10

method: 
```
public abstract class CoinViewRule : ConsensusRule
protected void UpdateUTXOSet(RuleContext context, Transaction transaction)
        {
            this.Logger.LogTrace("()");

            ChainedHeader index = context.ValidationContext.ChainedHeader;
            UnspentOutputSet view = (context as UtxoRuleContext).UnspentOutputSet; // this is always null

            view.Update(transaction, index.Height); // Exception here

            this.Logger.LogTrace("(-)");
        }
```

Logs:

info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:54.37.46.84]:26178' connected (outbound), agent '/Stratis:2.0.0.5/', height 532870
info: Stratis.Bitcoin.FullNode[0]
      Consensus Loop stopping
crit: Stratis.Bitcoin.FullNode[0]
      Consensus Loop threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CoinViewRule.UpdateUTXOSet(RuleContext context, Transaction transaction) in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CoinviewRule.cs:line 158
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PosCoinviewRule.UpdateCoinView(RuleContext context, Transaction transaction) in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PosCoinviewRule.cs:line 106
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CoinViewRule.<RunAsync>d__9.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CoinviewRule.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PosCoinviewRule.<RunAsync>d__4.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PosCoinviewRule.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Consensus.Rules.ConsensusRules.<ValidateAndExecuteAsync>d__35.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin\Consensus\Rules\ConsensusRules.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<ValidateAndExecuteBlockAsync>d__43.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 437
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<AcceptBlockAsync>d__40.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<PullerLoopAsync>d__38.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<<StartAsync>b__36_0>d.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
fail: Stratis.Bitcoin.FullNode[0]
      Consensus Loop threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CoinViewRule.UpdateUTXOSet(RuleContext context, Transaction transaction) in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CoinviewRule.cs:line 158
         at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PosCoinviewRule.UpdateCoinView(RuleContext context, Transaction transaction) in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PosCoinviewRule.cs:line 106
         at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.CoinViewRule.<RunAsync>d__9.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\CoinviewRule.cs:line 125
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PosCoinviewRule.<RunAsync>d__4.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PosCoinviewRule.cs:line 49
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Consensus.Rules.ConsensusRules.<ValidateAndExecuteAsync>d__35.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin\Consensus\Rules\ConsensusRules.cs:line 150
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<ValidateAndExecuteBlockAsync>d__43.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 437
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<AcceptBlockAsync>d__40.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 320
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<PullerLoopAsync>d__38.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 267
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<<StartAsync>b__36_0>d.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 201
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\workspace\blockchain\StratisBitcoinFullNode-sc-alpha\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:52.235.34.159]:26178' connected (outbound), agent 'mdennis-StratisBitcoin:1.1.12', height 532870

Please advice, thanks

**Comment by dangershony** [comment] 2018-08-28 13:05
There is a bug we are aware of that causes that (most likely some race condition) it will be useful to get this with full logs enabled.
Unfortunate the only work around is to resync the chain.

We have an idea of what might cause this.

**Comment by dangershony** [comment] 2018-08-28 13:10
I think its a duplicate of this
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1462

**Closed** 2018-12-04 19:08 UTC
Labels: bug, duplicate
