### ISSUE TITLE
CPU utilization spikes to 100%+ during minimal node activity

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#501] opened 2017-09-26 22:12 UTC
@dangershony @Aprogiena 
I'm running the FullNode with .NET core 2.0 on Ubuntu 16.04.3 LTS.

 After starting the Node with either `dotnet run` or `dotnet exec` I see through watching the **PID 10020 (dotnet)** in **HTOP** (interactive linux process viewer) and also using **pidstat** (Process monitor for tasks managed by linux kernel) that the node is sporadically causing CPU spikes over 100% and remain there for approximately 3-7 seconds at a time. Additionally I used **nethogs** a network packet monitoring tool to see network utilization of the process as well, which was miminal, and at most times 0kb/s

This may be an issue, due to the fact this is occurring while the fullnode is 100% synced, and no blocks are being downloaded, no changes in connections are occurring as far as I can see, and whilst minimal to no Disk I/O operations. (Including a screenshot here to better illustrate this). 

![image](https://user-images.githubusercontent.com/18432686/30886455-0c5bbbfc-a2e5-11e7-9b0a-34f724d19ac8.png)
**The Screenshot timestamp is 2017-09-26 time: 18:03:30**

Upper Right: HTOP, **101% CPU**
Upper Left:   Pidstat, **Disk I/O showing 0 kB/s read/write** 
Lower Left:   **Fullnode running with 100% synced blocks**
Lower Right: Nethogs, **Transfer activity: 0 kB/s sent/received**

**Comment by Aprogiena** [comment] 2017-09-27 07:18
I can confirm seeing the pattern on Windows 10, StratisD, fully synced node, testnet.

**Comment by dangershony** [comment] 2017-09-27 23:50
Ok we definitely need to investigate, any idea if this started after the 2.0 upgrade?

**Comment by Aprogiena** [comment] 2017-09-28 06:32
Sadly no, this is could start before or after, we don't have such information.

**Comment by bokobza** [comment] 2017-10-02 10:13
![](https://github.trello.services/images/mini-trello-icon.png) [[Perf] CPU utilization spikes to 100%+ during minimal node activity](https://trello.com/c/hi3H3qvL/273-perf-cpu-utilization-spikes-to-100-during-minimal-node-activity)

**Comment by Aprogiena** [comment] 2017-10-12 08:06
Currently I'm unable to reproduce this issue. It is either fixed or affected by the number of UTXOs in the wallet, which I previously had plenty, but recently consolidated and have not very many. I need to leave this issue open until I have 700 UTXOs again and check again then.

**Comment by dangershony** [comment] 2017-10-12 10:00
I believe this was fixed @D3m0nKingx did you have the Breeze UI open when you got the spikes?
If yes that was because of history and the issue was fixed.

**Comment by D3m0nKingx** [comment] 2017-10-12 10:44
The spikes occurred without Breeze active. I also just tested with and without Breeze UI running. and couldn't reproduce the issue.

**Comment by Aprogiena** [comment] 2017-10-12 12:04
I also got the CPU usage with plain raw StratisD, not even staking.

**Comment by dangershony** [comment] 2017-10-12 12:08
If neither can reproduce then lets close this and if it comes back we create a new issue?

**Comment by Aprogiena** [comment] 2017-10-12 12:10
I still have suspicion, so I will verify it and if it is negative, I will close it.

**Comment by Aprogiena** [comment] 2017-10-16 07:10
Even with 2000 UTXOs, I can no longer see this behavior. It's been said that an issue that could cause this was resolved and no one experienced this since, so I'm closing this as resolved.

**Closed by Aprogiena** 2017-10-16 07:10 UTC
