### ISSUE TITLE
Unable to spend rewards

### ISSUE THREAD

**Issue by StratisIain** [stratisproject/StratisBitcoinFullNode#2674] opened 2018-11-05 10:21 UTC
I have a node that has been staking for a few days and has got some staking rewards. 

Here is the address
https://chainz.cryptoid.info/strat-test/address.dws?TVzJhHXgcRY3F3AGmSHYq3h2GVM3eQDwj3.htm

I have mature staking rewards but am unable to send a transaction of full balance, I am presented  with "Not enough funds."

Steps to reproduce:

Network: TestNet
Create Wallet
Receive Funds (Example address above is 310,000)
Start Staking
Earn Staking Rewards
Wait for Staking Rewards to mature
Build Transaction 
`{
  "feeAmount": "1",
  "password": "Wallet3",
  "opReturnData": "",
  "walletName": "password",
  "accountName": "account 0",
  "destinationAddress": "TPcVgKfg2wHgABG3U5Rim7hKfk8mQPDWAH",
  "amount": "310000",
  "feeType": "high",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}`

**Comment by bokobza** [comment] 2018-11-05 10:48
@StratisIain thanks for the report.
Can you try without the feeamount? feeAmount will take over feeType if both are set.

**Comment by StratisIain** [comment] 2018-11-05 10:56
`{
  "password": "password",
  "opReturnData": "",
  "walletName": "Wallet3",
  "accountName": "account 0",
  "destinationAddress": "TPcVgKfg2wHgABG3U5Rim7hKfk8mQPDWAH",
  "amount": "310000",
  "feeType": "high",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}`

Still same issue

**Comment by bokobza** [comment] 2018-11-05 15:35
OK, the problem is something else.
Since this node is staking and outputs are being split, the wallet oscillates between a state of being able to send 310K coins to a state of just mining a coin and not having enough available matured outputs.

**Comment by bokobza** [comment] 2018-11-06 12:43
Created #2686 so I'm closing this.

**Closed by bokobza** 2018-11-06 12:43 UTC
Labels: UAT Issues, won't fix
