### ISSUE TITLE
Coinview race condition that leads to consensus loop stopping

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1462] opened 2018-05-30 21:41 UTC
Happened during IBD on BTC mainnet:

```
 Consensus Loop stopping
crit: Stratis.Bitcoin.FullNode[0]
      Consensus Loop threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Consensus.UnspentOutputSet.Update(Transaction transaction, Int32 height) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\UnspentOutputSet.cs:line 49
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PowCoinViewRule.UpdateCoinView(RuleContext context, Transaction transaction) in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PowCoinviewRule.cs:line 154
   at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.PowCoinViewRule.<RunAsync>d__3.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\PowCoinviewRule.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.Rules.ConsensusRules.<ValidateAndExecuteAsync>d__35.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\Rules\ConsensusRules.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<ValidateAndExecuteBlockAsync>d__41.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 462
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<AcceptBlockAsync>d__39.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 358
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<PullerLoopAsync>d__37.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Features.Consensus.ConsensusLoop.<<StartAsync>b__35_0>d.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin.Features.Consensus\ConsensusLoop.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\user\Desktop\StratisRepository\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 129
```

**Comment by bokobza** [comment] 2018-05-30 22:54
Is that from master, using the new BlockStore and ChainHeader?

**Comment by noescape00** [comment] 2018-05-31 15:50
>Is that from master, using the new BlockStore and ChainHeader?

Yes. But I'm pretty sure the bug is about validation, not new components- the coin that was retrieved from utxo set was null. 

>Interesting, what height did it happen at?

Around 300k

>Why do you think its a race condition?

We had very similar bug couple of months ago and investigated it- was the problem with CachedCoinView

>Do you have logs and any other info?

No, unfortunately. I usually disable logs during IBD

>On a restart does the node continue or is the db corrupt?

DB was corrupted after the restart.

**Comment by noescape00** [comment] 2018-05-31 15:51
Don't know if we wan't to fix this one, actually. Most likely this bug will be fixed after TheBigRefactoring is finished. Not entirely sure though.

**Comment by dangershony** [comment] 2018-06-01 11:35
Ok yeah so keep it open for now I guess in case it happens again.

**Comment by dangershony** [comment] 2018-08-17 14:40
On the activation branch this seems to be reproducible.
I have a data folder on bitcoin testnet that can reproduce this here.
https://stratisplatform-my.sharepoint.com/:u:/p/dan_gershony/EW6CNOLeBBRBnMZ13zK0iW8BlpCUfqgC9TDbYjcf0JGa_A?e=7YNBzc

**Comment by dangershony** [comment] 2018-09-14 10:18
Update: at some point we will make a stress test to try to produce this bug if not we close it.

**Comment by dangershony** [comment] 2018-09-28 10:13
This is likely fixed

**Closed by dangershony** 2018-09-28 10:13 UTC
Labels: Size M: 3-5 days, sp
